const capability = (id, title, purpose, description) => ({ id, title, purpose, description });

export const connectorCapabilities = [
  capability(
    'automated-testing',
    'Tests automatisés',
    'diagnostics',
    'Exécuter les assertions et contrats autorisés du projet via l’hôte.',
  ),
  capability(
    'code-quality',
    'Analyse du code',
    'diagnostics',
    'Syntaxe, types et conventions sur une version précise.',
  ),
  capability(
    'browser-testing',
    'Parcours navigateur',
    'diagnostics',
    'Scénarios, états et récupération dans un navigateur réel.',
  ),
  capability(
    'accessibility',
    'Accessibilité',
    'diagnostics',
    'Analyse automatisée et observations explicites, avec leurs limites.',
  ),
  capability(
    'observability',
    'Erreurs et traces',
    'diagnostics',
    'Diagnostics d’un environnement réellement instrumenté.',
  ),
  capability(
    'mail',
    'Envoi de mails',
    'application',
    'Choisir et intégrer un service ; aucun message envoyé par ce panneau.',
  ),
  capability(
    'database',
    'Base de données',
    'application',
    'Choisir le stockage et ses contrats, sans provisionnement implicite.',
  ),
  capability(
    'backend',
    'Backend applicatif',
    'application',
    'Relier un backend existant ou préparer son intégration.',
  ),
  capability(
    'authentication',
    'Authentification',
    'application',
    'Préparer les parcours et les contrôles d’accès du projet.',
  ),
  capability(
    'payments',
    'Paiements et abonnements',
    'application',
    'Préparer les encaissements, abonnements et événements de paiement.',
  ),
  capability(
    'commerce',
    'Commerce',
    'application',
    'Relier catalogue, panier et commandes à la boutique choisie.',
  ),
  capability(
    'storage',
    'Fichiers et stockage',
    'application',
    'Préparer le stockage objet et les règles d’accès aux fichiers.',
  ),
  capability(
    'ai',
    'Intelligence artificielle',
    'application',
    'Intégrer des modèles avec des limites de coût, de données et de qualité explicites.',
  ),
  capability(
    'version-control',
    'Dépôts et collaboration Git',
    'application',
    'Préparer les liens vers dépôts, issues et demandes de fusion.',
  ),
  capability(
    'cms',
    'Contenus et CMS',
    'application',
    'Relier des contenus structurés à leur interface de gestion.',
  ),
  capability(
    'messaging',
    'Messages et notifications',
    'application',
    'Préparer des canaux de communication et leurs autorisations.',
  ),
  capability(
    'productivity',
    'Documents et organisation',
    'application',
    'Relier documents, tables et calendriers aux parcours du projet.',
  ),
  capability(
    'analytics',
    'Mesure d’usage',
    'application',
    'Préparer les événements et rapports utiles au produit.',
  ),
  capability(
    'search',
    'Recherche applicative',
    'application',
    'Intégrer indexation, recherche et contrôle d’accès aux résultats.',
  ),
  capability(
    'hosting',
    'Hébergement',
    'application',
    'Préparer un déploiement compatible avec le runtime et les services du projet.',
  ),
];

const applicationCapabilities = connectorCapabilities
  .filter((entry) => entry.purpose === 'application')
  .map((entry) => entry.id);

const code = ['source-syntax', 'type-checking', 'linting', 'relative-imports'];
const tests = [
  'unit-tests',
  'integration-tests',
  'mutation-testing',
  'concurrency',
  'authorization',
  'server-validation',
];
const browser = [
  'end-to-end',
  'keyboard',
  'responsive',
  'ui-states',
  'network-recovery',
  'business-journey',
];
const observe = ['observability', 'api-latency', 'availability'];

function option(
  id,
  title,
  purpose,
  capabilities,
  transport,
  docs,
  description,
  cost,
  checkIds = [],
  limits = [],
) {
  return {
    id,
    title,
    purpose,
    capabilities,
    transport,
    docs,
    description,
    cost,
    checkIds,
    limits: [
      'Le Studio prépare le raccordement ; l’agent hôte exécute les outils autorisés et rapporte ses observations.',
      ...(purpose === 'application'
        ? [
            'Préparation d’intégration uniquement : aucune connexion, action externe, dépense ou mise en production automatique.',
          ]
        : []),
      ...limits,
    ],
  };
}

export const connectorOptions = [
  option(
    'node-test',
    'Runner de tests Node.js',
    'diagnostics',
    ['automated-testing'],
    'local',
    'https://nodejs.org/api/test.html',
    'Exécuter les tests existants dans un environnement autorisé par l’hôte.',
    'Logiciel libre local ; pas d’exécution de scripts de projet depuis ce panneau.',
    ['unit-tests', 'integration-tests', 'concurrency', 'authorization', 'server-validation'],
    [
      'Les tests exécutent le code : périmètre et isolation à valider par l’hôte. La pertinence des assertions reste à examiner.',
    ],
  ),
  option(
    'diagnostic-api',
    'Autre API de diagnostic',
    'diagnostics',
    ['code-quality', 'automated-testing', 'browser-testing', 'accessibility', 'observability'],
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Déclarer l’outil API autorisé et rapporter ses résultats structurés via l’hôte.',
    'Selon le fournisseur et les accès déjà disponibles.',
    [...code, ...tests, ...browser, 'semantics', ...observe],
  ),
  option(
    'node-check',
    'Node.js — syntaxe locale',
    'diagnostics',
    ['code-quality'],
    'local',
    'https://nodejs.org/api/cli.html#-c---check',
    'Analyse syntaxique sans exécuter le code du projet.',
    'Logiciel libre local ; ressources de la machine.',
    ['source-syntax'],
    ['Ne vérifie ni le comportement ni les types.'],
  ),
  option(
    'eslint',
    'ESLint',
    'diagnostics',
    ['code-quality'],
    'local',
    'https://eslint.org/docs/latest/integrate/nodejs-api',
    'Analyse locale avec règles et configuration explicitement autorisées.',
    'Logiciel libre local ; installation séparée si absent.',
    ['linting'],
  ),
  option(
    'playwright',
    'Playwright local',
    'diagnostics',
    ['browser-testing'],
    'local',
    'https://playwright.dev/docs/test-reporters',
    'Exécuter des scénarios autorisés et restituer leurs résultats.',
    'Logiciel libre local ; navigateur et dépendances requis.',
    browser,
  ),
  option(
    'playwright-mcp',
    'Playwright via MCP',
    'diagnostics',
    ['browser-testing'],
    'mcp',
    'https://github.com/microsoft/playwright-mcp',
    'Utiliser les outils du serveur MCP connecté à l’hôte.',
    'Serveur libre ; ressources de l’hôte et éventuels coûts d’agent distincts.',
    browser,
    ['Une liste d’outils n’est pas une preuve de parcours réussi.'],
  ),
  option(
    'axe-core',
    'axe-core',
    'diagnostics',
    ['accessibility'],
    'local',
    'https://www.deque.com/axe/axe-core/',
    'Analyse d’accessibilité automatisée dans un navigateur.',
    'MPL-2.0 ; moteur libre. Services commerciaux distincts.',
    ['semantics'],
    ['Les contrôles manuels restent nécessaires.'],
  ),
  option(
    'sentry',
    'Sentry API',
    'diagnostics',
    ['observability'],
    'api',
    'https://docs.sentry.io/api/',
    'Retour d’erreurs observées dans un projet Sentry autorisé.',
    'Selon l’offre, l’hébergement et les conditions du fournisseur.',
    ['observability'],
    ['Un projet instrumenté et des accès limités sont requis.'],
  ),
  option(
    'opentelemetry',
    'OpenTelemetry / collecteur existant',
    'diagnostics',
    ['observability'],
    'api',
    'https://opentelemetry.io/docs/',
    'Relier l’instrumentation aux données du collecteur réellement utilisé.',
    'Instrumentation libre ; exploitation et backend selon votre choix.',
    observe,
    ['OpenTelemetry ne fournit pas à lui seul un backend de stockage.'],
  ),
  option(
    'diagnostic-mcp',
    'Autre serveur MCP de diagnostic',
    'diagnostics',
    ['code-quality', 'automated-testing', 'browser-testing', 'accessibility', 'observability'],
    'mcp',
    'https://modelcontextprotocol.io/specification/2025-11-25/server/tools',
    'Déclarer un serveur hôte existant et ses capacités réellement observées.',
    'Dépend du serveur et de son fournisseur ; aucun accès ou forfait inclus.',
    [...code, ...tests, ...browser, 'semantics', ...observe],
  ),
  option(
    'smtp',
    'SMTP existant',
    'application',
    ['mail'],
    'api',
    'https://nodemailer.com/smtp',
    'Préparer un adaptateur SMTP vers le service choisi.',
    'Selon votre serveur ou fournisseur SMTP.',
    [],
    ['Aucun envoi de mail ni test de livraison automatique.'],
  ),
  option(
    'mailpit',
    'Mailpit local',
    'application',
    ['mail'],
    'local',
    'https://mailpit.axllent.org/docs/',
    'Boîte de réception de développement pour les essais locaux.',
    'Logiciel libre auto-hébergé ; ressources locales.',
    [],
    ['Capture de mails de test ; ne constitue pas un service de livraison en production.'],
  ),
  option(
    'resend',
    'Resend',
    'application',
    ['mail'],
    'api',
    'https://resend.com/docs/introduction',
    'Préparer l’intégration de l’API de mail choisie.',
    'Selon les quotas et conditions en vigueur du fournisseur.',
    [],
    ['Domaine, identité d’expéditeur et accès à configurer. Aucun envoi ici.'],
  ),
  option(
    'brevo',
    'Brevo',
    'application',
    ['mail', 'messaging'],
    'api',
    'https://developers.brevo.com/docs/getting-started',
    'Préparer les mails transactionnels et notifications SMS via les API Brevo.',
    'Selon les canaux, volumes, quotas et conditions du fournisseur.',
    [],
    [
      'Compte, expéditeurs et références d’accès requis ; aucune clé saisie, permission élargie ou notification envoyée ici.',
    ],
  ),
  option(
    'postgresql',
    'PostgreSQL',
    'application',
    ['database'],
    'local',
    'https://www.postgresql.org/docs/current/',
    'Base auto-hébergée ou déjà disponible sous votre contrôle.',
    'Logiciel libre ; hébergement et exploitation distincts.',
  ),
  option(
    'supabase',
    'Supabase',
    'application',
    ['database', 'backend', 'authentication'],
    'api',
    'https://supabase.com/docs',
    'Option de plateforme parmi les autres fournisseurs ; aucun choix imposé.',
    'Selon l’offre hébergée ou les ressources de l’auto-hébergement.',
  ),
  option(
    'appwrite',
    'Appwrite',
    'application',
    ['database', 'backend', 'authentication'],
    'api',
    'https://appwrite.io/docs',
    'Préparer une intégration Appwrite Cloud ou auto-hébergée.',
    'Selon l’offre hébergée ou les ressources de l’auto-hébergement.',
  ),
  option(
    'existing-backend',
    'Backend existant / autre fournisseur',
    'application',
    ['backend', 'database'],
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Réutiliser un service existant et préciser son contrat API dans la demande.',
    'Selon votre service et son fournisseur.',
    [],
    ['Le contrat et les capacités restent à examiner avec l’hôte.'],
  ),
  option(
    'keycloak',
    'Keycloak',
    'application',
    ['authentication'],
    'local',
    'https://www.keycloak.org/documentation',
    'Préparer une authentification sur un serveur Keycloak autorisé.',
    'Logiciel libre auto-hébergé ; exploitation à prévoir.',
  ),
  option(
    'auth0',
    'Auth0',
    'application',
    ['authentication'],
    'api',
    'https://auth0.com/docs',
    'Préparer une intégration d’identité avec ce fournisseur.',
    'Selon le contrat et l’offre en vigueur du fournisseur.',
  ),
  option(
    'stripe',
    'Stripe',
    'application',
    ['payments'],
    'api',
    'https://docs.stripe.com/payments',
    'Préparer paiements, abonnements et webhooks Stripe dans le projet.',
    'Frais et disponibilité selon le contrat, les opérations et le pays.',
    [],
    ['Compte et environnement de test requis ; aucun encaissement ni achat depuis le catalogue.'],
  ),
  option(
    'paddle',
    'Paddle',
    'application',
    ['payments'],
    'api',
    'https://developer.paddle.com/',
    'Préparer le paiement et les abonnements via le modèle de marchand officiel de Paddle.',
    'Selon le contrat, les produits éligibles et les transactions.',
    [],
    ['Éligibilité commerciale et séparation sandbox/production à vérifier ; aucun paiement ici.'],
  ),
  option(
    'shopify',
    'Shopify',
    'application',
    ['commerce'],
    'api',
    'https://shopify.dev/docs/api',
    'Préparer une boutique ou un parcours headless avec Storefront et Admin API.',
    'Boutique, application et services selon leurs offres respectives.',
    [],
    ['Boutique autorisée, version API et portées d’accès requises ; aucune commande créée ici.'],
  ),
  option(
    'woocommerce',
    'WooCommerce',
    'application',
    ['commerce'],
    'api',
    'https://developer.woocommerce.com/docs/apis/',
    'Relier les produits, paniers et commandes d’une boutique WooCommerce existante.',
    'Hébergement WordPress, extensions et exploitation à prévoir.',
    [],
    ['Distinguer Store API publique et API de gestion authentifiée ; aucun achat exécuté.'],
  ),
  option(
    's3',
    'Amazon S3',
    'application',
    ['storage'],
    'api',
    'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html',
    'Préparer le stockage objet, les accès privés et les transferts de fichiers.',
    'Stockage, requêtes et transferts selon la région et l’offre.',
    [],
    ['Bucket, région, politique IAM et durée de conservation à définir ; aucune ressource créée.'],
  ),
  option(
    'cloudflare-r2',
    'Cloudflare R2',
    'application',
    ['storage'],
    'api',
    'https://developers.cloudflare.com/r2/',
    'Préparer un stockage objet R2 via les interfaces documentées compatibles S3.',
    'Selon le stockage, les opérations et les conditions du fournisseur.',
    [],
    [
      'La compatibilité S3 doit être vérifiée pour les opérations utilisées ; aucun bucket provisionné.',
    ],
  ),
  option(
    'openai',
    'OpenAI',
    'application',
    ['ai'],
    'api',
    'https://developers.openai.com/api/docs',
    'Préparer des fonctions IA via l’API OpenAI et le modèle choisi pour le besoin.',
    'API facturée selon modèles, outils et consommation ; accès de chat distinct.',
    [],
    [
      'Clé côté serveur, budget, traitement des données et évaluations requis ; aucun appel de modèle ici.',
    ],
  ),
  option(
    'anthropic',
    'Anthropic',
    'application',
    ['ai'],
    'api',
    'https://platform.claude.com/docs/en/api/overview',
    'Préparer des fonctions IA avec l’API Claude et ses contrats de réponse.',
    'Selon les modèles, quotas et conditions de l’API.',
    [],
    ['Accès API, budget et politique de données à définir ; aucun abonnement supposé disponible.'],
  ),
  option(
    'gemini',
    'Google Gemini',
    'application',
    ['ai'],
    'api',
    'https://ai.google.dev/gemini-api/docs',
    'Préparer des fonctions IA avec la Gemini API et ses modalités de réponse.',
    'Selon le modèle, le palier et les conditions applicables à l’API.',
    [],
    ['Choisir le modèle et examiner quotas, données et budget ; aucun appel depuis ce panneau.'],
  ),
  option(
    'ollama',
    'Ollama local',
    'application',
    ['ai'],
    'local',
    'https://docs.ollama.com/api/introduction',
    'Préparer l’accès à une instance Ollama locale et à ses modèles disponibles.',
    'Ressources de la machine et conditions des modèles choisis.',
    [],
    [
      'Runtime et modèle installés séparément ; capacité matérielle à vérifier. Aucun téléchargement lancé.',
    ],
  ),
  option(
    'github',
    'GitHub',
    'application',
    ['version-control'],
    'api',
    'https://docs.github.com/en/rest',
    'Préparer l’intégration de dépôts, issues et pull requests via les API GitHub.',
    'Selon le compte, l’offre et les ressources utilisées.',
    [],
    [
      'Dépôts et permissions ciblés ; aucune publication, issue ou fusion créée par cette préparation.',
    ],
  ),
  option(
    'gitlab',
    'GitLab',
    'application',
    ['version-control'],
    'api',
    'https://docs.gitlab.com/api/rest/',
    'Préparer l’accès aux projets, issues et merge requests d’une instance GitLab.',
    'Selon l’offre hébergée ou l’exploitation de votre instance.',
    [],
    ['Version de l’instance et permissions à vérifier ; aucun pipeline ni merge request lancé.'],
  ),
  option(
    'strapi',
    'Strapi',
    'application',
    ['cms'],
    'api',
    'https://docs.strapi.io/cms/api/rest',
    'Relier les contenus d’un CMS Strapi via son API et ses modèles.',
    'Auto-hébergement ou offre cloud ; extensions et exploitation distinctes.',
    [],
    ['Instance, schémas et droits de lecture/édition requis ; aucune publication de contenu.'],
  ),
  option(
    'directus',
    'Directus',
    'application',
    ['cms', 'backend'],
    'api',
    'https://directus.com/docs/api',
    'Préparer des contenus et données exposés par les API REST ou GraphQL de Directus.',
    'Hébergement et conditions de licence ou d’offre à examiner.',
    [],
    [
      'Collections et permissions de l’instance à vérifier ; aucune migration ni édition de données.',
    ],
  ),
  option(
    'contentful',
    'Contentful',
    'application',
    ['cms'],
    'api',
    'https://www.contentful.com/developers/docs/references/api-basics/',
    'Relier la livraison et la gestion des contenus d’un espace Contentful.',
    'Selon l’offre, les espaces et les quotas du fournisseur.',
    [],
    ['Séparer accès de prévisualisation, lecture et gestion ; aucune publication de contenu.'],
  ),
  option(
    'sanity',
    'Sanity',
    'application',
    ['cms'],
    'api',
    'https://www.sanity.io/docs',
    'Préparer l’accès aux contenus structurés et à leur schéma Sanity.',
    'Selon le projet, les quotas et les services activés.',
    [],
    ['Projet, dataset et droits requis ; distinguer brouillons et contenus publiés.'],
  ),
  option(
    'slack',
    'Slack',
    'application',
    ['messaging'],
    'api',
    'https://docs.slack.dev/apis/web-api/',
    'Préparer notifications et interactions avec un espace Slack autorisé.',
    'Selon l’espace de travail, l’offre et les limites API.',
    [],
    ['Application et portées ciblées nécessaires ; aucun message envoyé par le catalogue.'],
  ),
  option(
    'discord',
    'Discord',
    'application',
    ['messaging'],
    'api',
    'https://docs.discord.com/developers/intro',
    'Préparer un bot ou des interactions dans des serveurs Discord autorisés.',
    'Selon l’hébergement du bot et les services utilisés.',
    [],
    ['Permissions, intents et serveur cible à définir ; aucun bot installé ni message envoyé.'],
  ),
  option(
    'telegram',
    'Telegram',
    'application',
    ['messaging'],
    'api',
    'https://core.telegram.org/bots/api',
    'Préparer les messages et interactions d’un bot Telegram.',
    'Hébergement et éventuelles fonctions payantes selon l’usage.',
    [],
    ['Bot et destinataires autorisés requis ; aucune conversation ni notification initiée ici.'],
  ),
  option(
    'twilio',
    'Twilio',
    'application',
    ['messaging'],
    'api',
    'https://www.twilio.com/docs/messaging/api',
    'Préparer des notifications SMS ou d’autres canaux documentés de Twilio Messaging.',
    'Numéros, canaux, destinations et messages selon leur tarification.',
    [],
    ['Expéditeurs et exigences du canal à examiner ; aucun numéro acheté ni message envoyé.'],
  ),
  option(
    'gmail',
    'Gmail',
    'application',
    ['mail', 'messaging'],
    'api',
    'https://developers.google.com/workspace/gmail/api/guides',
    'Préparer l’accès autorisé aux messages et brouillons d’une boîte Gmail.',
    'Selon le compte, les quotas et les services Google associés.',
    [],
    [
      'OAuth et portées à traiter dans l’hôte ; ne remplace pas par défaut un service de mail transactionnel.',
    ],
  ),
  option(
    'notion',
    'Notion',
    'application',
    ['productivity'],
    'api',
    'https://developers.notion.com/guides/get-started/overview',
    'Préparer les liens vers pages, blocs et données Notion autorisés.',
    'Selon le workspace, le forfait et les limites API.',
    [],
    ['L’intégration doit avoir accès aux pages ciblées ; aucun document partagé ou modifié ici.'],
  ),
  option(
    'airtable',
    'Airtable',
    'application',
    ['productivity'],
    'api',
    'https://support.airtable.com/articles/6292134965-getting-started-with-airtable-s-web-api',
    'Préparer l’accès aux tables et enregistrements de bases Airtable autorisées.',
    'Selon les bases, le forfait et les limites API.',
    [],
    ['Bases, tables et portées d’accès à préciser ; aucune écriture ni synchronisation lancée.'],
  ),
  option(
    'google-calendar',
    'Google Calendar',
    'application',
    ['productivity'],
    'api',
    'https://developers.google.com/workspace/calendar/api/guides/overview',
    'Préparer disponibilités, calendriers et événements avec les accès autorisés.',
    'Selon les comptes, quotas et services Google utilisés.',
    [],
    ['OAuth et agendas ciblés requis ; aucune invitation ni modification d’événement envoyée.'],
  ),
  option(
    'posthog',
    'PostHog',
    'application',
    ['analytics'],
    'api',
    'https://posthog.com/docs',
    'Préparer des événements produit et des analyses d’usage PostHog.',
    'Selon les volumes, fonctions et mode d’hébergement retenus.',
    [],
    ['Définir les événements et données collectées ; aucune télémétrie activée par le catalogue.'],
  ),
  option(
    'matomo',
    'Matomo',
    'application',
    ['analytics'],
    'api',
    'https://developer.matomo.org/',
    'Préparer le suivi d’usage et les rapports d’une instance Matomo choisie.',
    'Auto-hébergement ou offre cloud ; exploitation et extensions distinctes.',
    [],
    ['Instance, sites suivis et politique de collecte requis ; aucun suivi activé ici.'],
  ),
  option(
    'google-analytics',
    'Google Analytics',
    'application',
    ['analytics'],
    'api',
    'https://developers.google.com/analytics',
    'Préparer la collecte d’événements et les rapports Google Analytics.',
    'Selon la propriété, l’offre et les services associés.',
    [],
    ['Propriété, accès et règles de collecte à définir ; aucun tag ajouté automatiquement.'],
  ),
  option(
    'meilisearch',
    'Meilisearch',
    'application',
    ['search'],
    'api',
    'https://www.meilisearch.com/docs/getting_started/overview',
    'Préparer une recherche applicative dans des index Meilisearch.',
    'Auto-hébergement ou offre cloud ; ressources et exploitation distinctes.',
    [],
    [
      'Instance, schéma d’indexation et droits des résultats requis ; aucun index ni document créé.',
    ],
  ),
  option(
    'algolia',
    'Algolia',
    'application',
    ['search'],
    'api',
    'https://www.algolia.com/doc',
    'Préparer indexation et recherche applicative avec les API Algolia.',
    'Selon l’offre, les enregistrements et les requêtes.',
    [],
    ['Application, index et séparation des clés de recherche/administration requis.'],
  ),
  option(
    'cloudflare-workers',
    'Cloudflare Workers',
    'application',
    ['hosting', 'backend'],
    'api',
    'https://developers.cloudflare.com/workers/',
    'Préparer un déploiement sur Workers avec ses contraintes de runtime et ses bindings.',
    'Selon les requêtes, le calcul et les services associés.',
    [],
    ['Compatibilité du runtime à examiner ; aucun compte, domaine ou déploiement créé.'],
  ),
  option(
    'vercel',
    'Vercel',
    'application',
    ['hosting'],
    'api',
    'https://vercel.com/docs',
    'Préparer hébergement, builds et fonctions compatibles avec Vercel.',
    'Selon l’offre, les fonctions, le trafic et les ressources consommées.',
    [],
    ['Projet et variables à configurer selon le runtime ; aucune publication déclenchée.'],
  ),
  option(
    'netlify',
    'Netlify',
    'application',
    ['hosting'],
    'api',
    'https://docs.netlify.com/',
    'Préparer un site, son build et ses fonctions compatibles avec Netlify.',
    'Selon l’offre et les ressources utilisées.',
    [],
    ['Vérifier le build, le runtime et les services requis ; aucun site publié automatiquement.'],
  ),
  option(
    'application-api',
    'Autre API applicative',
    'application',
    applicationCapabilities,
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Préparer l’intégration d’un service API existant à partir de son contrat réel.',
    'Selon le service choisi ; aucun fournisseur ni accès inclus.',
    [],
    [
      'Déclarer seulement les opérations documentées et autorisées. Le catalogue ne fournit aucun client API universel.',
    ],
  ),
  option(
    'application-mcp',
    'Autre service via MCP',
    'application',
    applicationCapabilities,
    'mcp',
    'https://modelcontextprotocol.io/specification/2025-11-25/server/tools',
    'Préparer l’usage d’outils d’un serveur MCP déjà accessible à l’agent hôte.',
    'Selon le serveur, son hébergement et le fournisseur des opérations.',
    [],
    [
      'Les capacités proposées sont des catégories possibles, pas des outils garantis. Un accès MCP de l’agent ne crée pas le service de l’application.',
    ],
  ),
];

export const capabilityChecks = {
  'automated-testing': tests,
  'code-quality': code,
  'browser-testing': browser,
  accessibility: ['semantics'],
  observability: observe,
};

export function connectorOffers(checkId) {
  return connectorOptions.filter((entry) => entry.checkIds.includes(checkId));
}
