const capability = (id, title, purpose, description) => ({ id, title, purpose, description });

export const connectorCapabilities = [
  capability(
    'automated-testing',
    'Tests automatisés',
    'diagnostics',
    'Exécuter les assertions et contrats autorisés du projet via l’hôte.',
  ),
  capability(
    'code-quality',
    'Analyse du code',
    'diagnostics',
    'Syntaxe, types et conventions sur une version précise.',
  ),
  capability(
    'browser-testing',
    'Parcours navigateur',
    'diagnostics',
    'Scénarios, états et récupération dans un navigateur réel.',
  ),
  capability(
    'accessibility',
    'Accessibilité',
    'diagnostics',
    'Analyse automatisée et observations explicites, avec leurs limites.',
  ),
  capability(
    'observability',
    'Erreurs et traces',
    'diagnostics',
    'Diagnostics d’un environnement réellement instrumenté.',
  ),
  capability(
    'mail',
    'Envoi de mails',
    'application',
    'Choisir et intégrer un service ; aucun message envoyé par ce panneau.',
  ),
  capability(
    'database',
    'Base de données',
    'application',
    'Choisir le stockage et ses contrats, sans provisionnement implicite.',
  ),
  capability(
    'backend',
    'Backend applicatif',
    'application',
    'Relier un backend existant ou préparer son intégration.',
  ),
  capability(
    'authentication',
    'Authentification',
    'application',
    'Préparer les parcours et les contrôles d’accès du projet.',
  ),
  capability(
    'payments',
    'Paiements et abonnements',
    'application',
    'Préparer les encaissements, abonnements et événements de paiement.',
  ),
  capability(
    'commerce',
    'Commerce',
    'application',
    'Relier catalogue, panier et commandes à la boutique choisie.',
  ),
  capability(
    'storage',
    'Fichiers et stockage',
    'application',
    'Préparer le stockage objet et les règles d’accès aux fichiers.',
  ),
  capability(
    'ai',
    'Intelligence artificielle',
    'application',
    'Intégrer des modèles avec des limites de coût, de données et de qualité explicites.',
  ),
  capability(
    'version-control',
    'Dépôts et collaboration Git',
    'application',
    'Préparer les liens vers dépôts, issues et demandes de fusion.',
  ),
  capability(
    'cms',
    'Contenus et CMS',
    'application',
    'Relier des contenus structurés à leur interface de gestion.',
  ),
  capability(
    'messaging',
    'Messages et notifications',
    'application',
    'Préparer des canaux de communication et leurs autorisations.',
  ),
  capability(
    'productivity',
    'Documents et organisation',
    'application',
    'Relier documents, tables et calendriers aux parcours du projet.',
  ),
  capability(
    'analytics',
    'Mesure d’usage',
    'application',
    'Préparer les événements et rapports utiles au produit.',
  ),
  capability(
    'search',
    'Recherche applicative',
    'application',
    'Intégrer indexation, recherche et contrôle d’accès aux résultats.',
  ),
  capability(
    'hosting',
    'Hébergement',
    'application',
    'Préparer un déploiement compatible avec le runtime et les services du projet.',
  ),
];

const applicationCapabilities = connectorCapabilities
  .filter((entry) => entry.purpose === 'application')
  .map((entry) => entry.id);

const code = ['source-syntax', 'type-checking', 'linting', 'relative-imports'];
const tests = [
  'unit-tests',
  'integration-tests',
  'mutation-testing',
  'concurrency',
  'authorization',
  'server-validation',
];
const browser = [
  'end-to-end',
  'keyboard',
  'responsive',
  'ui-states',
  'network-recovery',
  'business-journey',
];
const observe = ['observability', 'api-latency', 'availability'];

function option(
  id,
  title,
  purpose,
  capabilities,
  transport,
  docs,
  description,
  cost,
  checkIds = [],
  limits = [],
) {
  return {
    id,
    title,
    purpose,
    capabilities,
    transport,
    docs,
    description,
    cost,
    checkIds,
    limits: [
      'Le Studio prépare le raccordement ; l’agent hôte exécute les outils autorisés et rapporte ses observations.',
      ...(purpose === 'application'
        ? [
            'Préparation d’intégration uniquement : aucune connexion, action externe, dépense ou mise en production automatique.',
          ]
        : []),
      ...limits,
    ],
  };
}

export const connectorOptions = [
  option(
    'node-test',
    'Runner de tests Node.js',
    'diagnostics',
    ['automated-testing'],
    'local',
    'https://nodejs.org/api/test.html',
    'Exécuter les tests existants dans un environnement autorisé par l’hôte.',
    'Logiciel libre local ; pas d’exécution de scripts de projet depuis ce panneau.',
    ['unit-tests', 'integration-tests', 'concurrency', 'authorization', 'server-validation'],
    [
      'Les tests exécutent le code : périmètre et isolation à valider par l’hôte. La pertinence des assertions reste à examiner.',
    ],
  ),
  option(
    'diagnostic-api',
    'Autre API de diagnostic',
    'diagnostics',
    ['code-quality', 'automated-testing', 'browser-testing', 'accessibility', 'observability'],
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Déclarer l’outil API autorisé et rapporter ses résultats structurés via l’hôte.',
    'Selon le fournisseur et les accès déjà disponibles.',
    [...code, ...tests, ...browser, 'semantics', ...observe],
  ),
  option(
    'node-check',
    'Node.js — syntaxe locale',
    'diagnostics',
    ['code-quality'],
    'local',
    'https://nodejs.org/api/cli.html#-c---check',
    'Analyse syntaxique sans exécuter le code du projet.',
    'Logiciel libre local ; ressources de la machine.',
    ['source-syntax'],
    ['Ne vérifie ni le comportement ni les types.'],
  ),
  option(
    'eslint',
    'ESLint',
    'diagnostics',
    ['code-quality'],
    'local',
    'https://eslint.org/docs/latest/integrate/nodejs-api',
    'Analyse locale avec règles et configuration explicitement autorisées.',
    'Logiciel libre local ; installation séparée si absent.',
    ['linting'],
  ),
  option(
    'playwright',
    'Playwright local',
    'diagnostics',
    ['browser-testing'],
    'local',
    'https://playwright.dev/docs/test-reporters',
    'Exécuter des scénarios autorisés et restituer leurs résultats.',
    'Logiciel libre local ; navigateur et dépendances requis.',
    browser,
  ),
  option(
    'playwright-mcp',
    'Playwright via MCP',
    'diagnostics',
    ['browser-testing'],
    'mcp',
    'https://github.com/microsoft/playwright-mcp',
    'Utiliser les outils du serveur MCP connecté à l’hôte.',
    'Serveur libre ; ressources de l’hôte et éventuels coûts d’agent distincts.',
    browser,
    ['Une liste d’outils n’est pas une preuve de parcours réussi.'],
  ),
  option(
    'axe-core',
    'axe-core',
    'diagnostics',
    ['accessibility'],
    'local',
    'https://www.deque.com/axe/axe-core/',
    'Analyse d’accessibilité automatisée dans un navigateur.',
    'MPL-2.0 ; moteur libre. Services commerciaux distincts.',
    ['semantics'],
    ['Les contrôles manuels restent nécessaires.'],
  ),
  option(
    'sentry',
    'Sentry API',
    'diagnostics',
    ['observability'],
    'api',
    'https://docs.sentry.io/api/',
    'Retour d’erreurs observées dans un projet Sentry autorisé.',
    'Selon l’offre, l’hébergement et les conditions du fournisseur.',
    ['observability'],
    ['Un projet instrumenté et des accès limités sont requis.'],
  ),
  option(
    'opentelemetry',
    'OpenTelemetry / collecteur existant',
    'diagnostics',
    ['observability'],
    'api',
    'https://opentelemetry.io/docs/',
    'Relier l’instrumentation aux données du collecteur réellement utilisé.',
    'Instrumentation libre ; exploitation et backend selon votre choix.',
    observe,
    ['OpenTelemetry ne fournit pas à lui seul un backend de stockage.'],
  ),
  option(
    'diagnostic-mcp',
    'Autre serveur MCP de diagnostic',
    'diagnostics',
    ['code-quality', 'automated-testing', 'browser-testing', 'accessibility', 'observability'],
    'mcp',
    'https://modelcontextprotocol.io/specification/2025-11-25/server/tools',
    'Déclarer un serveur hôte existant et ses capacités réellement observées.',
    'Dépend du serveur et de son fournisseur ; aucun accès ou forfait inclus.',
    [...code, ...tests, ...browser, 'semantics', ...observe],
  ),
  option(
    'smtp',
    'SMTP existant',
    'application',
    ['mail'],
    'api',
    'https://nodemailer.com/smtp',
    'Préparer un adaptateur SMTP vers le service choisi.',
    'Selon votre serveur ou fournisseur SMTP.',
    [],
    ['Aucun envoi de mail ni test de livraison automatique.'],
  ),
  option(
    'mailpit',
    'Mailpit local',
    'application',
    ['mail'],
    'local',
    'https://mailpit.axllent.org/docs/',
    'Boîte de réception de développement pour les essais locaux.',
    'Logiciel libre auto-hébergé ; ressources locales.',
    [],
    ['Capture de mails de test ; ne constitue pas un service de livraison en production.'],
  ),
  option(
    'resend',
    'Resend',
    'application',
    ['mail'],
    'api',
    'https://resend.com/docs/introduction',
    'Préparer l’intégration de l’API de mail choisie.',
    'Selon les quotas et conditions en vigueur du fournisseur.',
    [],
    ['Domaine, identité d’expéditeur et accès à configurer. Aucun envoi ici.'],
  ),
  option(
    'brevo',
    'Brevo',
    'application',
    ['mail', 'messaging'],
    'api',
    'https://developers.brevo.com/docs/getting-started',
    'Préparer les mails transactionnels et notifications SMS via les API Brevo.',
    'Selon les canaux, volumes, quotas et conditions du fournisseur.',
    [],
    [
      'Compte, expéditeurs et références d’accès requis ; aucune clé saisie, permission élargie ou notification envoyée ici.',
    ],
  ),
  option(
    'postgresql',
    'PostgreSQL',
    'application',
    ['database'],
    'local',
    'https://www.postgresql.org/docs/current/',
    'Base auto-hébergée ou déjà disponible sous votre contrôle.',
    'Logiciel libre ; hébergement et exploitation distincts.',
  ),
  option(
    'supabase',
    'Supabase',
    'application',
    ['database', 'backend', 'authentication'],
    'api',
    'https://supabase.com/docs',
    'Option de plateforme parmi les autres fournisseurs ; aucun choix imposé.',
    'Selon l’offre hébergée ou les ressources de l’auto-hébergement.',
  ),
  option(
    'appwrite',
    'Appwrite',
    'application',
    ['database', 'backend', 'authentication'],
    'api',
    'https://appwrite.io/docs',
    'Préparer une intégration Appwrite Cloud ou auto-hébergée.',
    'Selon l’offre hébergée ou les ressources de l’auto-hébergement.',
  ),
  option(
    'existing-backend',
    'Backend existant / autre fournisseur',
    'application',
    ['backend', 'database'],
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Réutiliser un service existant et préciser son contrat API dans la demande.',
    'Selon votre service et son fournisseur.',
    [],
    ['Le contrat et les capacités restent à examiner avec l’hôte.'],
  ),
  option(
    'keycloak',
    'Keycloak',
    'application',
    ['authentication'],
    'local',
    'https://www.keycloak.org/documentation',
    'Préparer une authentification sur un serveur Keycloak autorisé.',
    'Logiciel libre auto-hébergé ; exploitation à prévoir.',
  ),
  option(
    'auth0',
    'Auth0',
    'application',
    ['authentication'],
    'api',
    'https://auth0.com/docs',
    'Préparer une intégration d’identité avec ce fournisseur.',
    'Selon le contrat et l’offre en vigueur du fournisseur.',
  ),
  option(
    'stripe',
    'Stripe',
    'application',
    ['payments'],
    'api',
    'https://docs.stripe.com/payments',
    'Préparer paiements, abonnements et webhooks Stripe dans le projet.',
    'Frais et disponibilité selon le contrat, les opérations et le pays.',
    [],
    ['Compte et environnement de test requis ; aucun encaissement ni achat depuis le catalogue.'],
  ),
  option(
    'paddle',
    'Paddle',
    'application',
    ['payments'],
    'api',
    'https://developer.paddle.com/',
    'Préparer le paiement et les abonnements via le modèle de marchand officiel de Paddle.',
    'Selon le contrat, les produits éligibles et les transactions.',
    [],
    ['Éligibilité commerciale et séparation sandbox/production à vérifier ; aucun paiement ici.'],
  ),
  option(
    'shopify',
    'Shopify',
    'application',
    ['commerce'],
    'api',
    'https://shopify.dev/docs/api',
    'Préparer une boutique ou un parcours headless avec Storefront et Admin API.',
    'Boutique, application et services selon leurs offres respectives.',
    [],
    ['Boutique autorisée, version API et portées d’accès requises ; aucune commande créée ici.'],
  ),
  option(
    'woocommerce',
    'WooCommerce',
    'application',
    ['commerce'],
    'api',
    'https://developer.woocommerce.com/docs/apis/',
    'Relier les produits, paniers et commandes d’une boutique WooCommerce existante.',
    'Hébergement WordPress, extensions et exploitation à prévoir.',
    [],
    ['Distinguer Store API publique et API de gestion authentifiée ; aucun achat exécuté.'],
  ),
  option(
    's3',
    'Amazon S3',
    'application',
    ['storage'],
    'api',
    'https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html',
    'Préparer le stockage objet, les accès privés et les transferts de fichiers.',
    'Stockage, requêtes et transferts selon la région et l’offre.',
    [],
    ['Bucket, région, politique IAM et durée de conservation à définir ; aucune ressource créée.'],
  ),
  option(
    'cloudflare-r2',
    'Cloudflare R2',
    'application',
    ['storage'],
    'api',
    'https://developers.cloudflare.com/r2/',
    'Préparer un stockage objet R2 via les interfaces documentées compatibles S3.',
    'Selon le stockage, les opérations et les conditions du fournisseur.',
    [],
    [
      'La compatibilité S3 doit être vérifiée pour les opérations utilisées ; aucun bucket provisionné.',
    ],
  ),
  option(
    'openai',
    'OpenAI',
    'application',
    ['ai'],
    'api',
    'https://developers.openai.com/api/docs',
    'Préparer des fonctions IA via l’API OpenAI et le modèle choisi pour le besoin.',
    'API facturée selon modèles, outils et consommation ; accès de chat distinct.',
    [],
    [
      'Clé côté serveur, budget, traitement des données et évaluations requis ; aucun appel de modèle ici.',
    ],
  ),
  option(
    'anthropic',
    'Anthropic',
    'application',
    ['ai'],
    'api',
    'https://platform.claude.com/docs/en/api/overview',
    'Préparer des fonctions IA avec l’API Claude et ses contrats de réponse.',
    'Selon les modèles, quotas et conditions de l’API.',
    [],
    ['Accès API, budget et politique de données à définir ; aucun abonnement supposé disponible.'],
  ),
  option(
    'gemini',
    'Google Gemini',
    'application',
    ['ai'],
    'api',
    'https://ai.google.dev/gemini-api/docs',
    'Préparer des fonctions IA avec la Gemini API et ses modalités de réponse.',
    'Selon le modèle, le palier et les conditions applicables à l’API.',
    [],
    ['Choisir le modèle et examiner quotas, données et budget ; aucun appel depuis ce panneau.'],
  ),
  option(
    'ollama',
    'Ollama local',
    'application',
    ['ai'],
    'local',
    'https://docs.ollama.com/api/introduction',
    'Préparer l’accès à une instance Ollama locale et à ses modèles disponibles.',
    'Ressources de la machine et conditions des modèles choisis.',
    [],
    [
      'Runtime et modèle installés séparément ; capacité matérielle à vérifier. Aucun téléchargement lancé.',
    ],
  ),
  option(
    'github',
    'GitHub · API de l’application',
    'application',
    ['version-control'],
    'api',
    'https://docs.github.com/en/rest',
    'Préparer l’intégration de dépôts, issues et pull requests via les API GitHub.',
    'Selon le compte, l’offre et les ressources utilisées.',
    [],
    [
      'Dépôts et permissions ciblés ; aucune publication, issue ou fusion créée par cette préparation.',
    ],
  ),
  option(
    'gitlab',
    'GitLab',
    'application',
    ['version-control'],
    'api',
    'https://docs.gitlab.com/api/rest/',
    'Préparer l’accès aux projets, issues et merge requests d’une instance GitLab.',
    'Selon l’offre hébergée ou l’exploitation de votre instance.',
    [],
    ['Version de l’instance et permissions à vérifier ; aucun pipeline ni merge request lancé.'],
  ),
  option(
    'strapi',
    'Strapi',
    'application',
    ['cms'],
    'api',
    'https://docs.strapi.io/cms/api/rest',
    'Relier les contenus d’un CMS Strapi via son API et ses modèles.',
    'Auto-hébergement ou offre cloud ; extensions et exploitation distinctes.',
    [],
    ['Instance, schémas et droits de lecture/édition requis ; aucune publication de contenu.'],
  ),
  option(
    'directus',
    'Directus',
    'application',
    ['cms', 'backend'],
    'api',
    'https://directus.com/docs/api',
    'Préparer des contenus et données exposés par les API REST ou GraphQL de Directus.',
    'Hébergement et conditions de licence ou d’offre à examiner.',
    [],
    [
      'Collections et permissions de l’instance à vérifier ; aucune migration ni édition de données.',
    ],
  ),
  option(
    'contentful',
    'Contentful',
    'application',
    ['cms'],
    'api',
    'https://www.contentful.com/developers/docs/references/api-basics/',
    'Relier la livraison et la gestion des contenus d’un espace Contentful.',
    'Selon l’offre, les espaces et les quotas du fournisseur.',
    [],
    ['Séparer accès de prévisualisation, lecture et gestion ; aucune publication de contenu.'],
  ),
  option(
    'sanity',
    'Sanity',
    'application',
    ['cms'],
    'api',
    'https://www.sanity.io/docs',
    'Préparer l’accès aux contenus structurés et à leur schéma Sanity.',
    'Selon le projet, les quotas et les services activés.',
    [],
    ['Projet, dataset et droits requis ; distinguer brouillons et contenus publiés.'],
  ),
  option(
    'slack',
    'Slack',
    'application',
    ['messaging'],
    'api',
    'https://docs.slack.dev/apis/web-api/',
    'Préparer notifications et interactions avec un espace Slack autorisé.',
    'Selon l’espace de travail, l’offre et les limites API.',
    [],
    ['Application et portées ciblées nécessaires ; aucun message envoyé par le catalogue.'],
  ),
  option(
    'discord',
    'Discord',
    'application',
    ['messaging'],
    'api',
    'https://docs.discord.com/developers/intro',
    'Préparer un bot ou des interactions dans des serveurs Discord autorisés.',
    'Selon l’hébergement du bot et les services utilisés.',
    [],
    ['Permissions, intents et serveur cible à définir ; aucun bot installé ni message envoyé.'],
  ),
  option(
    'telegram',
    'Telegram',
    'application',
    ['messaging'],
    'api',
    'https://core.telegram.org/bots/api',
    'Préparer les messages et interactions d’un bot Telegram.',
    'Hébergement et éventuelles fonctions payantes selon l’usage.',
    [],
    ['Bot et destinataires autorisés requis ; aucune conversation ni notification initiée ici.'],
  ),
  option(
    'twilio',
    'Twilio',
    'application',
    ['messaging'],
    'api',
    'https://www.twilio.com/docs/messaging/api',
    'Préparer des notifications SMS ou d’autres canaux documentés de Twilio Messaging.',
    'Numéros, canaux, destinations et messages selon leur tarification.',
    [],
    ['Expéditeurs et exigences du canal à examiner ; aucun numéro acheté ni message envoyé.'],
  ),
  option(
    'gmail',
    'Gmail',
    'application',
    ['mail', 'messaging'],
    'api',
    'https://developers.google.com/workspace/gmail/api/guides',
    'Préparer l’accès autorisé aux messages et brouillons d’une boîte Gmail.',
    'Selon le compte, les quotas et les services Google associés.',
    [],
    [
      'OAuth et portées à traiter dans l’hôte ; ne remplace pas par défaut un service de mail transactionnel.',
    ],
  ),
  option(
    'notion',
    'Notion',
    'application',
    ['productivity'],
    'api',
    'https://developers.notion.com/guides/get-started/overview',
    'Préparer les liens vers pages, blocs et données Notion autorisés.',
    'Selon le workspace, le forfait et les limites API.',
    [],
    ['L’intégration doit avoir accès aux pages ciblées ; aucun document partagé ou modifié ici.'],
  ),
  option(
    'airtable',
    'Airtable',
    'application',
    ['productivity'],
    'api',
    'https://support.airtable.com/articles/6292134965-getting-started-with-airtable-s-web-api',
    'Préparer l’accès aux tables et enregistrements de bases Airtable autorisées.',
    'Selon les bases, le forfait et les limites API.',
    [],
    ['Bases, tables et portées d’accès à préciser ; aucune écriture ni synchronisation lancée.'],
  ),
  option(
    'google-calendar',
    'Google Calendar',
    'application',
    ['productivity'],
    'api',
    'https://developers.google.com/workspace/calendar/api/guides/overview',
    'Préparer disponibilités, calendriers et événements avec les accès autorisés.',
    'Selon les comptes, quotas et services Google utilisés.',
    [],
    ['OAuth et agendas ciblés requis ; aucune invitation ni modification d’événement envoyée.'],
  ),
  option(
    'posthog',
    'PostHog',
    'application',
    ['analytics'],
    'api',
    'https://posthog.com/docs',
    'Préparer des événements produit et des analyses d’usage PostHog.',
    'Selon les volumes, fonctions et mode d’hébergement retenus.',
    [],
    ['Définir les événements et données collectées ; aucune télémétrie activée par le catalogue.'],
  ),
  option(
    'matomo',
    'Matomo',
    'application',
    ['analytics'],
    'api',
    'https://developer.matomo.org/',
    'Préparer le suivi d’usage et les rapports d’une instance Matomo choisie.',
    'Auto-hébergement ou offre cloud ; exploitation et extensions distinctes.',
    [],
    ['Instance, sites suivis et politique de collecte requis ; aucun suivi activé ici.'],
  ),
  option(
    'google-analytics',
    'Google Analytics',
    'application',
    ['analytics'],
    'api',
    'https://developers.google.com/analytics',
    'Préparer la collecte d’événements et les rapports Google Analytics.',
    'Selon la propriété, l’offre et les services associés.',
    [],
    ['Propriété, accès et règles de collecte à définir ; aucun tag ajouté automatiquement.'],
  ),
  option(
    'meilisearch',
    'Meilisearch',
    'application',
    ['search'],
    'api',
    'https://www.meilisearch.com/docs/getting_started/overview',
    'Préparer une recherche applicative dans des index Meilisearch.',
    'Auto-hébergement ou offre cloud ; ressources et exploitation distinctes.',
    [],
    [
      'Instance, schéma d’indexation et droits des résultats requis ; aucun index ni document créé.',
    ],
  ),
  option(
    'algolia',
    'Algolia',
    'application',
    ['search'],
    'api',
    'https://www.algolia.com/doc',
    'Préparer indexation et recherche applicative avec les API Algolia.',
    'Selon l’offre, les enregistrements et les requêtes.',
    [],
    ['Application, index et séparation des clés de recherche/administration requis.'],
  ),
  option(
    'cloudflare-workers',
    'Cloudflare Workers',
    'application',
    ['hosting', 'backend'],
    'api',
    'https://developers.cloudflare.com/workers/',
    'Préparer un déploiement sur Workers avec ses contraintes de runtime et ses bindings.',
    'Selon les requêtes, le calcul et les services associés.',
    [],
    ['Compatibilité du runtime à examiner ; aucun compte, domaine ou déploiement créé.'],
  ),
  option(
    'vercel',
    'Vercel',
    'application',
    ['hosting'],
    'api',
    'https://vercel.com/docs',
    'Préparer hébergement, builds et fonctions compatibles avec Vercel.',
    'Selon l’offre, les fonctions, le trafic et les ressources consommées.',
    [],
    ['Projet et variables à configurer selon le runtime ; aucune publication déclenchée.'],
  ),
  option(
    'netlify',
    'Netlify',
    'application',
    ['hosting'],
    'api',
    'https://docs.netlify.com/',
    'Préparer un site, son build et ses fonctions compatibles avec Netlify.',
    'Selon l’offre et les ressources utilisées.',
    [],
    ['Vérifier le build, le runtime et les services requis ; aucun site publié automatiquement.'],
  ),
  option(
    'application-api',
    'Autre API applicative',
    'application',
    applicationCapabilities,
    'api',
    'https://spec.openapis.org/oas/latest.html',
    'Préparer l’intégration d’un service API existant à partir de son contrat réel.',
    'Selon le service choisi ; aucun fournisseur ni accès inclus.',
    [],
    [
      'Déclarer seulement les opérations documentées et autorisées. Le catalogue ne fournit aucun client API universel.',
    ],
  ),
  option(
    'application-mcp',
    'Autre service via MCP',
    'application',
    applicationCapabilities,
    'mcp',
    'https://modelcontextprotocol.io/specification/2025-11-25/server/tools',
    'Préparer l’usage d’outils d’un serveur MCP déjà accessible à l’agent hôte.',
    'Selon le serveur, son hébergement et le fournisseur des opérations.',
    [],
    [
      'Les capacités proposées sont des catégories possibles, pas des outils garantis. Un accès MCP de l’agent ne crée pas le service de l’application.',
    ],
  ),
];

export const capabilityChecks = {
  'automated-testing': tests,
  'code-quality': code,
  'browser-testing': browser,
  accessibility: ['semantics'],
  observability: observe,
};

export function connectorOffers(checkId) {
  return connectorOptions.filter((entry) => entry.checkIds.includes(checkId));
}

// Presentation only: durable IDs, permissions and preparation inputs remain canonical.
const englishCapabilities = {
  'automated-testing': [
    'Automated tests',
    'Run the project’s authorized assertions and contracts through the host.',
  ],
  'code-quality': ['Code analysis', 'Syntax, types and conventions for a specific version.'],
  'browser-testing': ['Browser journeys', 'Scenarios, states and recovery in a real browser.'],
  accessibility: [
    'Accessibility',
    'Automated analysis and explicit observations, with their limitations.',
  ],
  observability: [
    'Errors and traces',
    'Diagnostics from an environment that is actually instrumented.',
  ],
  mail: ['Email delivery', 'Choose and integrate a service; this panel sends no messages.'],
  database: ['Database', 'Choose storage and its contracts without implicit provisioning.'],
  backend: ['Application backend', 'Connect an existing backend or prepare its integration.'],
  authentication: ['Authentication', 'Prepare the project’s journeys and access controls.'],
  payments: ['Payments and subscriptions', 'Prepare payments, subscriptions and payment events.'],
  commerce: ['Commerce', 'Connect the catalog, cart and orders to the selected store.'],
  storage: ['Files and storage', 'Prepare object storage and file access rules.'],
  ai: ['Artificial intelligence', 'Integrate models with explicit cost, data and quality limits.'],
  'version-control': [
    'Git repositories and collaboration',
    'Prepare links to repositories, issues and merge requests.',
  ],
  cms: ['Content and CMS', 'Connect structured content to its management interface.'],
  messaging: [
    'Messages and notifications',
    'Prepare communication channels and their permissions.',
  ],
  productivity: [
    'Documents and organization',
    'Connect documents, tables and calendars to project journeys.',
  ],
  analytics: ['Usage analytics', 'Prepare events and reports that serve the product.'],
  search: ['Application search', 'Integrate indexing, search and access controls for results.'],
  hosting: ['Hosting', 'Prepare deployment compatible with the project’s runtime and services.'],
};

// Each entry supplies title, description, cost and any option-specific limitations.
const englishOptions = {
  'node-test': [
    'Node.js test runner',
    'Run existing tests in a host-authorized environment.',
    'Local open-source software; this panel does not execute project scripts.',
    'Tests execute code: the host must validate scope and isolation. Assertion relevance still needs review.',
  ],
  'diagnostic-api': [
    'Other diagnostic API',
    'Declare an authorized API tool and report its structured results through the host.',
    'Depends on the provider and available access.',
  ],
  'node-check': [
    'Node.js — local syntax',
    'Analyze syntax without executing project code.',
    'Local open-source software; machine resources.',
    'Checks neither behavior nor types.',
  ],
  eslint: [
    'ESLint',
    'Local analysis with explicitly authorized rules and configuration.',
    'Local open-source software; separate installation if unavailable.',
  ],
  playwright: [
    'Local Playwright',
    'Run authorized scenarios and return their results.',
    'Local open-source software; browser and dependencies required.',
  ],
  'playwright-mcp': [
    'Playwright via MCP',
    'Use tools from the MCP server connected to the host.',
    'Open-source server; host resources and any agent costs are separate.',
    'A tool list is not evidence of a successful journey.',
  ],
  'axe-core': [
    'axe-core',
    'Automated accessibility analysis in a browser.',
    'MPL-2.0; open-source engine. Commercial services are separate.',
    'Manual checks remain necessary.',
  ],
  sentry: [
    'Sentry API',
    'Report errors observed in an authorized Sentry project.',
    'Depends on the plan, hosting and provider terms.',
    'An instrumented project and restricted access are required.',
  ],
  opentelemetry: [
    'OpenTelemetry / existing collector',
    'Connect instrumentation to data from the collector actually in use.',
    'Open-source instrumentation; operations and backend depend on your choice.',
    'OpenTelemetry alone does not provide a storage backend.',
  ],
  'diagnostic-mcp': [
    'Other diagnostic MCP server',
    'Declare an existing host server and its actually observed capabilities.',
    'Depends on the server and provider; no access or plan included.',
  ],
  smtp: [
    'Existing SMTP',
    'Prepare an SMTP adapter for the selected service.',
    'Depends on your SMTP server or provider.',
    'No email is sent and no delivery test runs automatically.',
  ],
  mailpit: [
    'Local Mailpit',
    'A development inbox for local testing.',
    'Self-hosted open-source software; local resources.',
    'Captures test emails; it is not a production delivery service.',
  ],
  resend: [
    'Resend',
    'Prepare integration with the selected email API.',
    'Subject to the provider’s current quotas and terms.',
    'Configure the domain, sender identity and access. No sending here.',
  ],
  brevo: [
    'Brevo',
    'Prepare transactional emails and SMS notifications through Brevo APIs.',
    'Depends on channels, volumes, quotas and provider terms.',
    'Account, senders and access references required; no key entered, permissions expanded or notification sent here.',
  ],
  postgresql: [
    'PostgreSQL',
    'A self-hosted database or one already available under your control.',
    'Open-source software; hosting and operations are separate.',
  ],
  supabase: [
    'Supabase',
    'One platform option among other providers; no choice is imposed.',
    'Depends on the hosted plan or self-hosting resources.',
  ],
  appwrite: [
    'Appwrite',
    'Prepare an Appwrite Cloud or self-hosted integration.',
    'Depends on the hosted plan or self-hosting resources.',
  ],
  'existing-backend': [
    'Existing backend / other provider',
    'Reuse an existing service and specify its API contract in the request.',
    'Depends on your service and provider.',
    'The host still needs to review the contract and capabilities.',
  ],
  keycloak: [
    'Keycloak',
    'Prepare authentication on an authorized Keycloak server.',
    'Self-hosted open-source software; operations must be planned.',
  ],
  auth0: [
    'Auth0',
    'Prepare identity integration with this provider.',
    'Subject to the provider’s current contract and plan.',
  ],
  stripe: [
    'Stripe',
    'Prepare Stripe payments, subscriptions and webhooks in the project.',
    'Fees and availability depend on the contract, operations and country.',
    'Account and test environment required; no payment collected or purchase made from this catalog.',
  ],
  paddle: [
    'Paddle',
    'Prepare payments and subscriptions using Paddle’s merchant-of-record model.',
    'Depends on the contract, eligible products and transactions.',
    'Check commercial eligibility and sandbox/production separation; no payment here.',
  ],
  shopify: [
    'Shopify',
    'Prepare a store or headless journey with the Storefront and Admin APIs.',
    'Store, application and services follow their respective plans.',
    'Authorized store, API version and access scopes required; no order created here.',
  ],
  woocommerce: [
    'WooCommerce',
    'Connect products, carts and orders from an existing WooCommerce store.',
    'Plan for WordPress hosting, extensions and operations.',
    'Distinguish the public Store API from the authenticated management API; no purchase executed.',
  ],
  s3: [
    'Amazon S3',
    'Prepare object storage, private access and file transfers.',
    'Storage, requests and transfers depend on region and plan.',
    'Define bucket, region, IAM policy and retention period; no resource created.',
  ],
  'cloudflare-r2': [
    'Cloudflare R2',
    'Prepare R2 object storage through documented S3-compatible interfaces.',
    'Depends on storage, operations and provider terms.',
    'Verify S3 compatibility for the operations used; no bucket provisioned.',
  ],
  openai: [
    'OpenAI',
    'Prepare AI features through the OpenAI API and a model chosen for the need.',
    'API billing depends on models, tools and usage; chat access is separate.',
    'Server-side key, budget, data handling and evaluations required; no model call here.',
  ],
  anthropic: [
    'Anthropic',
    'Prepare AI features with the Claude API and its response contracts.',
    'Depends on API models, quotas and terms.',
    'Define API access, budget and data policy; no subscription assumed available.',
  ],
  gemini: [
    'Google Gemini',
    'Prepare AI features with the Gemini API and its response formats.',
    'Depends on the model, tier and applicable API terms.',
    'Choose the model and review quotas, data and budget; no call from this panel.',
  ],
  ollama: [
    'Local Ollama',
    'Prepare access to a local Ollama instance and its available models.',
    'Machine resources and terms of the selected models.',
    'Runtime and model installed separately; verify hardware capacity. No download started.',
  ],
  github: [
    'GitHub · Application API',
    'Prepare repository, issue and pull request integration through GitHub APIs.',
    'Depends on the account, plan and resources used.',
    'Target specific repositories and permissions; this preparation creates no publication, issue or merge.',
  ],
  gitlab: [
    'GitLab',
    'Prepare access to projects, issues and merge requests on a GitLab instance.',
    'Depends on the hosted plan or operation of your instance.',
    'Check instance version and permissions; no pipeline or merge request started.',
  ],
  strapi: [
    'Strapi',
    'Connect Strapi CMS content through its API and models.',
    'Self-hosting or cloud plan; extensions and operations are separate.',
    'Instance, schemas and read/edit permissions required; no content published.',
  ],
  directus: [
    'Directus',
    'Prepare content and data exposed through Directus REST or GraphQL APIs.',
    'Review hosting, licensing and plan terms.',
    'Check instance collections and permissions; no migration or data editing.',
  ],
  contentful: [
    'Contentful',
    'Connect content delivery and management for a Contentful space.',
    'Depends on the provider’s plan, spaces and quotas.',
    'Separate preview, read and management access; no content published.',
  ],
  sanity: [
    'Sanity',
    'Prepare access to structured content and its Sanity schema.',
    'Depends on the project, quotas and enabled services.',
    'Project, dataset and permissions required; distinguish drafts from published content.',
  ],
  slack: [
    'Slack',
    'Prepare notifications and interactions with an authorized Slack workspace.',
    'Depends on the workspace, plan and API limits.',
    'Application and targeted scopes required; the catalog sends no messages.',
  ],
  discord: [
    'Discord',
    'Prepare a bot or interactions in authorized Discord servers.',
    'Depends on bot hosting and services used.',
    'Define permissions, intents and target server; no bot installed or message sent.',
  ],
  telegram: [
    'Telegram',
    'Prepare messages and interactions for a Telegram bot.',
    'Hosting and any paid features depend on usage.',
    'Authorized bot and recipients required; no conversation or notification initiated here.',
  ],
  twilio: [
    'Twilio',
    'Prepare SMS notifications or other documented Twilio Messaging channels.',
    'Numbers, channels, destinations and messages follow their pricing.',
    'Review senders and channel requirements; no number purchased or message sent.',
  ],
  gmail: [
    'Gmail',
    'Prepare authorized access to messages and drafts in a Gmail inbox.',
    'Depends on the account, quotas and associated Google services.',
    'Handle OAuth and scopes in the host; this is not a default replacement for transactional email delivery.',
  ],
  notion: [
    'Notion',
    'Prepare links to authorized Notion pages, blocks and data.',
    'Depends on the workspace, plan and API limits.',
    'The integration needs access to the selected pages; no document shared or changed here.',
  ],
  airtable: [
    'Airtable',
    'Prepare access to tables and records in authorized Airtable bases.',
    'Depends on bases, plan and API limits.',
    'Specify bases, tables and access scopes; no write or synchronization started.',
  ],
  'google-calendar': [
    'Google Calendar',
    'Prepare availability, calendars and events with authorized access.',
    'Depends on accounts, quotas and Google services used.',
    'OAuth and targeted calendars required; no invitation or event update sent.',
  ],
  posthog: [
    'PostHog',
    'Prepare product events and usage analytics with PostHog.',
    'Depends on volume, features and hosting mode.',
    'Define collected events and data; the catalog enables no telemetry.',
  ],
  matomo: [
    'Matomo',
    'Prepare usage tracking and reports for a selected Matomo instance.',
    'Self-hosting or cloud plan; operations and extensions are separate.',
    'Instance, tracked sites and collection policy required; no tracking enabled here.',
  ],
  'google-analytics': [
    'Google Analytics',
    'Prepare event collection and Google Analytics reports.',
    'Depends on the property, plan and associated services.',
    'Define property, access and collection rules; no tag added automatically.',
  ],
  meilisearch: [
    'Meilisearch',
    'Prepare application search in Meilisearch indexes.',
    'Self-hosting or cloud plan; resources and operations are separate.',
    'Instance, indexing schema and result permissions required; no index or document created.',
  ],
  algolia: [
    'Algolia',
    'Prepare indexing and application search with Algolia APIs.',
    'Depends on the plan, records and requests.',
    'Application, indexes and separation of search/administration keys required.',
  ],
  'cloudflare-workers': [
    'Cloudflare Workers',
    'Prepare deployment to Workers with its runtime constraints and bindings.',
    'Depends on requests, compute and associated services.',
    'Review runtime compatibility; no account, domain or deployment created.',
  ],
  vercel: [
    'Vercel',
    'Prepare hosting, builds and functions compatible with Vercel.',
    'Depends on the plan, functions, traffic and resources consumed.',
    'Configure the project and variables for the runtime; no publication triggered.',
  ],
  netlify: [
    'Netlify',
    'Prepare a site, build and functions compatible with Netlify.',
    'Depends on the plan and resources used.',
    'Check the build, runtime and required services; no site published automatically.',
  ],
  'application-api': [
    'Other application API',
    'Prepare integration with an existing API service based on its actual contract.',
    'Depends on the selected service; no provider or access included.',
    'Declare only documented and authorized operations. The catalog provides no universal API client.',
  ],
  'application-mcp': [
    'Other service via MCP',
    'Prepare use of tools from an MCP server already accessible to the host agent.',
    'Depends on the server, its hosting and the provider of its operations.',
    'Suggested capabilities are possible categories, not guaranteed tools. Agent MCP access does not create the application’s service.',
  ],
};

export function projectConnectorCatalog(locale = 'en') {
  const catalog = structuredClone({
    capabilities: connectorCapabilities,
    options: connectorOptions,
  });
  if (locale === 'fr') return catalog;
  for (const entry of catalog.capabilities) {
    [entry.title, entry.description] = englishCapabilities[entry.id];
  }
  for (const entry of catalog.options) {
    const [title, description, cost, ...limits] = englishOptions[entry.id];
    Object.assign(entry, {
      title,
      description,
      cost,
      limits: [
        'Studio prepares the connection; the host agent executes authorized tools and reports observations.',
        ...(entry.purpose === 'application'
          ? [
              'Integration preparation only: no automatic connection, external action, spending or production deployment.',
            ]
          : []),
        ...limits,
      ],
    });
  }
  return catalog;
}
