// Declarative catalogue: adding a technique does not install or execute its tool.
export const qualityCategories = [
  ['functional', 'Fonctionnel'],
  ['performance', 'Performance'],
  ['accessibility', 'Accessibilité'],
  ['security', 'Sécurité'],
  ['reliability', 'Fiabilité'],
  ['operations', 'Exploitation'],
  ['business', 'Métier'],
].map(([id, label]) => ({ id, label }));

const local = (id, title, category, tool, objective, adapter, scope = 'code') => ({
  id,
  title,
  category,
  tool,
  objective,
  adapter,
  scope,
  execution: 'studio',
});
const external = (id, title, category, tool, objective, scope = 'all') => ({
  id,
  title,
  category,
  tool,
  objective,
  scope,
  execution: 'external',
  reason: 'Cette technique nécessite un outil ou une session dédiée non pilotée par ce Studio.',
  nextAction: `Exécuter ${tool} dans un environnement autorisé, puis conserver une preuve liée à cette version.`,
});

export const qualityCatalog = [
  local(
    'source-syntax',
    'Syntaxe des sources',
    'functional',
    'Node --check / parseur TypeScript installé',
    'Repérer les erreurs de syntaxe sans exécuter le programme.',
    'syntax',
  ),
  local(
    'react-strict-build',
    'Compilation React stricte',
    'functional',
    'Compilateur contrôlé React / TypeScript strict',
    'Vérifier les types et compiler le profil React pris en charge, sans exécuter le programme ou ses scripts.',
    'reactBuild',
    'reactProfile',
  ),
  local(
    'relative-imports',
    'Résolution des imports relatifs',
    'functional',
    'AST TypeScript + manifeste de la version',
    'Vérifier que les imports statiques relatifs pointent vers un fichier de cette version.',
    'imports',
  ),
  local(
    'json-format',
    'Documents JSON',
    'functional',
    'JSON.parse',
    'Vérifier le format des documents JSON sans exécuter leur contenu.',
    'json',
    'json',
  ),
  external(
    'type-checking',
    'Typage et contrats statiques',
    'functional',
    'TypeScript tsc --noEmit',
    'Vérifier la cohérence des types avec la configuration et les dépendances du projet.',
    'code',
  ),
  external(
    'linting',
    'Lint et conventions du projet',
    'functional',
    'ESLint et règles du projet',
    'Contrôler les conventions configurées sans assimiler le lint à un test de comportement.',
    'code',
  ),
  external(
    'unit-tests',
    'Tests unitaires et assertions',
    'functional',
    'Runner de tests du projet',
    'Exercer la logique et examiner la pertinence des assertions.',
  ),
  external(
    'integration-tests',
    'Intégration et contrats',
    'functional',
    'Runner et services du projet',
    'Vérifier les contrats entre modules et services.',
  ),
  external(
    'end-to-end',
    'Parcours de bout en bout',
    'functional',
    'Playwright ou navigateur autorisé',
    'Exécuter les parcours réels, y compris les cas limites.',
    'frontend',
  ),
  external(
    'mutation-testing',
    'Pertinence par mutation',
    'functional',
    'Outil de mutation adapté au projet',
    'Éprouver si les assertions détectent des défauts introduits.',
  ),
  local(
    'bundle-size',
    'Inventaire du bundle compilé',
    'performance',
    'Manifeste et taille des artefacts',
    'Mesurer les octets compilés ; aucune latence ni performance utilisateur déduite.',
    'bundle',
    'compiled',
  ),
  external(
    'loading',
    'Chargement, réseau et cache',
    'performance',
    'DevTools Network / Lighthouse',
    'Mesurer les ressources, le cache et le chargement.',
    'frontend',
  ),
  external(
    'responsiveness',
    'Réactivité et tâches longues',
    'performance',
    'Profiler du navigateur',
    'Mesurer les tâches JavaScript qui retardent les interactions.',
    'frontend',
  ),
  external(
    'react-renders',
    'Rendus React',
    'performance',
    'React Profiler',
    'Mesurer les rendus et leurs causes.',
    'react',
  ),
  external(
    'api-latency',
    'Latences API et tracing',
    'performance',
    'Profiler backend / OpenTelemetry',
    'Mesurer les temps et erreurs d’une requête.',
    'backend',
  ),
  external(
    'database-queries',
    'Requêtes, index et N+1',
    'performance',
    'EXPLAIN et profiler de base',
    'Examiner les plans de requêtes sur une base autorisée.',
    'database',
  ),
  external(
    'memory',
    'Mémoire et allocations',
    'performance',
    'Heap profiler',
    'Observer les allocations et rechercher les fuites.',
  ),
  external(
    'load',
    'Charge, débit et endurance',
    'performance',
    'k6 ou outil autorisé',
    'Mesurer débit, erreurs et stabilité sous charge.',
    'backend',
  ),
  external(
    'keyboard',
    'Clavier et focus',
    'accessibility',
    'Revue navigateur manuelle',
    'Parcourir les actions et vérifier le focus visible.',
    'frontend',
  ),
  external(
    'semantics',
    'Sémantique, libellés et contrastes',
    'accessibility',
    'Analyse automatisée + revue manuelle',
    'Vérifier les noms accessibles, la structure et les contrastes.',
    'frontend',
  ),
  external(
    'responsive',
    'Responsive et compatibilité',
    'accessibility',
    'Navigateurs et tailles représentatives',
    'Vérifier le rendu, le défilement et la compatibilité.',
    'frontend',
  ),
  external(
    'ui-states',
    'États vides, chargements et erreurs',
    'accessibility',
    'Parcours navigateur',
    'Vérifier les états utiles et les moyens de récupération.',
    'frontend',
  ),
  local(
    'secret-markers',
    'Marqueurs explicites de secrets',
    'security',
    'Détecteur borné de formats sensibles',
    'Repérer des clés privées PEM et formats de jetons connus ; valeurs masquées.',
    'secrets',
    'text',
  ),
  external(
    'authorization',
    'Autorisations et isolation',
    'security',
    'Tests API avec identités de test',
    'Vérifier les limites d’accès côté serveur.',
    'backend',
  ),
  external(
    'server-validation',
    'Validation serveur',
    'security',
    'Tests de contrats et entrées invalides',
    'Éprouver les entrées reçues par le serveur.',
    'backend',
  ),
  external(
    'dependencies',
    'Dépendances et analyse statique',
    'security',
    'Analyseur SAST / audit du verrou installé',
    'Examiner les dépendances et les chemins risqués.',
  ),
  external(
    'dynamic-security',
    'Sécurité dynamique autorisée',
    'security',
    'Scanner configuré pour la cible autorisée',
    'Examiner une cible explicitement autorisée.',
    'backend',
  ),
  external(
    'network-recovery',
    'Coupures, délais et reprise',
    'reliability',
    'Injection de fautes réseau',
    'Vérifier les timeouts, les erreurs et la conservation des saisies.',
    'frontend',
  ),
  external(
    'concurrency',
    'Concurrence et idempotence',
    'reliability',
    'Tests d’intégration concurrents',
    'Éprouver les transactions, doublons et mises à jour concurrentes.',
    'backend',
  ),
  external(
    'backup',
    'Sauvegarde et restauration',
    'reliability',
    'Exercice de restauration',
    'Restaurer une copie autorisée et confronter les données.',
  ),
  external(
    'observability',
    'Logs, exceptions et traces',
    'operations',
    'Instrumentation et collecteur du projet',
    'Observer une exécution avec des données sensibles masquées.',
  ),
  external(
    'availability',
    'Disponibilité et alertes',
    'operations',
    'Sondes et alertes du projet',
    'Vérifier un service réellement lancé.',
    'backend',
  ),
  external(
    'rollback',
    'Déploiement et retour arrière',
    'operations',
    'Pipeline autorisé du projet',
    'Éprouver la reprise et le retour arrière sans publier depuis ce contrôle.',
  ),
  external(
    'costs',
    'Coût et consommation',
    'operations',
    'Mesures du fournisseur et du runtime',
    'Rapprocher la consommation réellement mesurée du périmètre.',
  ),
  external(
    'business-journey',
    'Critères métier du projet',
    'business',
    'Scénarios issus du cadrage',
    'Vérifier les critères du projet ; aucun scénario sectoriel n’est inventé.',
  ),
];

export function projectCapabilities(revision, sources) {
  const text = sources.map((file) => file.content).join('\n');
  const paths = revision.files.map((file) => file.path);
  let reactProfile = false;
  try {
    const packageSource = sources.find((file) => file.path === 'package.json');
    reactProfile = Boolean(
      packageSource && JSON.parse(packageSource.content)?.devmethod?.profile === 'react-ts',
    );
  } catch {
    /* Invalid JSON is diagnosed separately; never infer a supported compiler profile. */
  }
  return {
    all: true,
    text: sources.length > 0,
    code: paths.some((file) => /\.(?:[mc]?js|jsx|tsx?)$/.test(file)),
    json: paths.some((file) => file.endsWith('.json')),
    frontend: paths.some((file) => /\.(?:html|tsx|jsx|css)$/.test(file)),
    react: /["']react(?:["'/])/.test(text),
    reactProfile,
    backend:
      paths.some((file) => /(?:^|\/)(?:server|backend|api)(?:\/|\.)/.test(file)) ||
      /(?:from\s*["'](?:express|fastify|koa|@nestjs\/)|from\s+(?:fastapi|flask))/.test(text),
    database:
      /(?:["'](?:pg|mysql2?|mongoose|sqlite3|better-sqlite3|@prisma\/client)["']|from\s+(?:sqlalchemy|psycopg))/.test(
        text,
      ),
    compiled: Boolean(revision.compilation?.files?.length),
  };
}
